### PR TITLE
#7480: Add timeout support 2

### PR DESCRIPTION
**Pull request by ruslanlazin**
The last deploy problem was caused by bug in core Python lib `httplib` 
https://bugs.python.org/issue14721
`httplib` doesn't specify content-length header for POST requests without data, so it cannot pass our nginx ( "Bad request") 
Old `LiveAgent-api-python`  inserted string 'null' to request with empty body, so error did not happen.
According to change log in was fixed in Python version 2.7.4rc1. 
We use 2.7.5 but `httplib`  in our distributive is old, not fixed. 

We cannot just increase Python version cause it is a `system` part of CentOS7.  There are workarounds how to use to different Python 2.7 versions on the same machine, but I'm not sure we need to implement them.

~~In order to make API working with old Python versions `empty string` is used in requests without body instead of `None`~~
In order to make API working with old Python versions `Content-length` header is set manually for requests with empty body.

PR also  revert "Revert "#7480: Add timeout support"

### CODE REVIEW

**Comment by ruslanlazin** [comment]
Updated version 1.0.16 is running now on x.asterisk.support.linode-de.

**Comment by ruslanlazin** [comment]
Found errors in log, checking

**Comment by ruslanlazin** [comment]
Errors were caused by https://github.com/QualityUnit/la-issues/issues/7928
Phone servers work with different LA versions, so added extra check can be removed when all LA accounts will be > version of #7928 fix 
Lib manually updated on 1/2.asterisk.support.linode-de
Seems OK now.

**Review by mbebjak — APPROVED** [review]

**Comment by ruslanlazin** [comment]
Swagger 2.3.x has issue with Unicode strings. (https://github.com/swagger-api/swagger-codegen/pull/7560)
Regenerated with Swagger 2.4.0
Also  `Content-length` header is set manually for requests with empty body.
Tested on 1/2.asterisk.support.linode-de since 04.01 -> no Errors.
@mbebjak Could you please review last changes?

**Review by mbebjak — APPROVED** [review]

**Pull request merged**
